services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: university
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      DB_URL: postgresql+psycopg2://app:${POSTGRES_PASSWORD}@db:5432/university
      UPLOAD_DIR: /data/uploads
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - uploads:/data/uploads
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    environment:
      VITE_API_URL: http://localhost:5000/api/v1
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
  uploads:

